### ISSUE TITLE
verifyPermissions ,this method I think it should return flase default.

### ISSUE THREAD

**Issue by 18626216800** [tajchert/Nammu#14]
verifyPermissions ,this method I think it should return flase default.
if i askForPermission twice with one Permission,it will return true the first time.

**Comment by tajchert** [comment]
> verifyPermissions ,this method I think it should return flase default.
There is no difference in this. Current way is to check if any of provided permissions is not granted. So changing it to default = false, would require changing expected way of working this method, if you see better way please make pull request on this, and I don't see a scenario when it would produce false result due to default = true.

For second issue please open another issue with a scenario to reproduce it.
